#!/bin/bash

# Simply calls docker run with the correct arguments to bring the container
# up in an interactive BASH shell 
docker run --rm -it -v"(pwd)":/home connorfuhrman/pytorch-ece696b:latest /bin/bash